package com.tangotori.app.data.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

@Database(
    entities = [
        EntryRow::class,
        KanjiRow::class,
        ReadingRow::class,
        SenseRow::class,
        GlossRow::class,
        // Added in v2 for the kanji breakdown section on Anki cards.
        KanjiDicRow::class,
    ],
    version = 3,
    exportSchema = true,
)
abstract class JmdictDatabase : RoomDatabase() {
    abstract fun jmdictDao(): JmdictDao

    companion object {
        private const val DB_NAME = "jmdict.db"

        /**
         * Builds the DB. If a pre-built asset `assets/jmdict.db` ships with the APK,
         * Room copies it on first access via [createFromAsset]. If you choose the
         * download-on-first-launch route, copy the downloaded file into the
         * databases directory at the path returned by [Context.getDatabasePath]
         * before building.
         */
        fun build(context: Context): JmdictDatabase =
            Room.databaseBuilder(context, JmdictDatabase::class.java, DB_NAME)
                // The asset is generated by `./gradlew :tools:jmdict-builder:run`
                // and lives at app/src/main/assets/jmdict.db. Room verifies
                // its identityHash on first open — the builder reads that hash
                // from app/schemas so the prepackaged DB matches.
                .createFromAsset("jmdict.db")
                .fallbackToDestructiveMigration()
                .build()
    }
}
